export const CartConstants = {
    GET_CART_REQUEST: 'GET_CART_REQUEST',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    GET_CART_FAILURE: 'GET_CART_FAILURE',

    ADD_CART_ITEM_REQUEST: 'ADD_CART_ITEM_REQUEST',
    ADD_CART_ITEM_SUCCESS: 'ADD_CART_ITEM_SUCCESS',
    ADD_CART_ITEM_FAILURE: 'ADD_CART_ITEM_FAILURE',

    REMOVE_CART_ITEM_REQUEST: 'REMOVE_CART_ITEM_REQUEST',
    REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
    REMOVE_CART_ITEM_FAILURE: 'REMOVE_CART_ITEM_FAILURE',

    UPDATE_CART_ITEM_REQUEST: 'UPDATE_CART_ITEM_REQUEST',
    UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
    UPDATE_CART_ITEM_FAILURE: 'UPDATE_CART_ITEM_FAILURE',

    RESET_CART_REQUEST: 'RESET_CART_REQUEST',
    RESET_CART_SUCCESS: 'RESET_CART_SUCCESS',
    RESET_CART_FAILURE: 'RESET_CART_FAILURE',

};
