export const CardConstants = {

    GET_ALL_CARDS_REQUEST: 'GET_ALL_CARDS_REQUEST',
    GET_ALL_CARDS_SUCCESS: 'GET_ALL_CARDS_SUCCESS',
    GET_ALL_CARDS_FAILURE: 'GET_ALL_CARDS_FAILURE',

    GET_CARD_REQUEST: 'GET_CARD_REQUEST',
    GET_CARD_SUCCESS: 'GET_CARD_SUCCESS',
    GET_CARD_FAILURE: 'GET_CARD_FAILURE',

    ADD_CARD_ITEM_REQUEST: 'ADD_CARD_ITEM_REQUEST',
    ADD_CARD_ITEM_SUCCESS: 'ADD_CARD_ITEM_SUCCESS',
    ADD_CARD_ITEM_FAILURE: 'ADD_CARD_ITEM_FAILURE',

    REMOVE_CARD_ITEM_REQUEST: 'REMOVE_CARD_ITEM_REQUEST',
    REMOVE_CARD_ITEM_SUCCESS: 'REMOVE_CARD_ITEM_SUCCESS',
    REMOVE_CARD_ITEM_FAILURE: 'REMOVE_CARD_ITEM_FAILURE',

    UPDATE_CARD_ITEM_REQUEST: 'UPDATE_CARD_ITEM_REQUEST',
    UPDATE_CARD_ITEM_SUCCESS: 'UPDATE_CARD_ITEM_SUCCESS',
    UPDATE_CARD_ITEM_FAILURE: 'UPDATE_CARD_ITEM_FAILURE',

    RESET_CARD_REQUEST: 'RESET_CARD_REQUEST',
    RESET_CARD_SUCCESS: 'RESET_CARD_SUCCESS',
    RESET_CARD_FAILURE: 'RESET_CARD_FAILURE',

};
