export const OrderConstant = {
    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    GET_ALl_ONGOING_ORDERS_REQUEST: 'GET_ALl_ONGOING_ORDERS_REQUEST',
    GET_ALl_ONGOING_ORDERS_SUCCESS: 'GET_ALl_ONGOING_ORDERS_SUCCESS',
    GET_ALl_ONGOING_ORDERS_FAILURE: 'GET_ALl_ONGOING_ORDERS_FAILURE',

    GET_ALl_COMPLETE_ORDERS_REQUEST: 'GET_ALl_COMPLETE_ORDERS_REQUEST',
    GET_ALl_COMPLETE_ORDERS_SUCCESS: 'GET_ALl_COMPLETE_ORDERS_SUCCESS',
    GET_ALl_COMPLETE_ORDERS_FAILURE: 'GET_ALl_COMPLETE_ORDERS_FAILURE',

    GET_ALl_CANCELLED_ORDERS_REQUEST: 'GET_ALl_CANCELLED_ORDERS_REQUEST',
    GET_ALl_CANCELLED_ORDERS_SUCCESS: 'GET_ALl_CANCELLED_ORDERS_SUCCESS',
    GET_ALl_CANCELLED_ORDERS_FAILURE: 'GET_ALl_CANCELLED_ORDERS_FAILURE',
};
