export const CategoryConstants = {
    GET_ALl_CATEGORIES_REQUEST: 'GET_ALl_CATEGORIES_REQUEST',
    GET_ALl_CATEGORIES_SUCCESS: 'GET_ALl_CATEGORIES_SUCCESS',
    GET_ALl_CATEGORIES_FAILURE: 'GET_ALl_CATEGORIES_FAILURE',
};
