export const ProductConstants = {

    GET_ALl_RECOMMENDED_PRODUCTS_REQUEST: 'GET_ALl_RECOMMENDED_PRODUCTS_REQUEST',
    GET_ALl_RECOMMENDED_PRODUCTS_SUCCESS: 'GET_ALl_RECOMMENDED_PRODUCTS_SUCCESS',
    GET_ALl_RECOMMENDED_PRODUCTS_FAILURE: 'GET_ALl_RECOMMENDED_PRODUCTS_FAILURE',

    GET_ALl_RELEVANT_PRODUCTS_REQUEST: 'GET_ALl_RELEVANT_PRODUCTS_REQUEST',
    GET_ALl_RELEVANT_PRODUCTS_SUCCESS: 'GET_ALl_RELEVANT_PRODUCTS_SUCCESS',
    GET_ALl_RELEVANT_PRODUCTS_FAILURE: 'GET_ALl_RELEVANT_PRODUCTS_FAILURE',
    RESET_ALl_RELEVANT_PRODUCTS: 'RESET_ALl_RELEVANT_PRODUCTS',

    GET_ALl_PRODUCTS_BY_CATEGORY_REQUEST: 'GET_ALl_PRODUCTS_BY_CATEGORY_REQUEST',
    GET_ALl_PRODUCTS_BY_CATEGORY_SUCCESS: 'GET_ALl_PRODUCTS_BY_CATEGORY_SUCCESS',
    GET_ALl_PRODUCTS_BY_CATEGORY_FAILURE: 'GET_ALl_PRODUCTS_BY_CATEGORY_FAILURE',
    RESET_ALl_PRODUCTS_BY_CATEGORY: 'RESET_ALl_PRODUCTS_BY_CATEGORY',

    GET_PRODUCT_VARIANTS_REQUEST: 'GET_PRODUCT_VARIANTS_REQUEST',
    GET_PRODUCT_VARIANTS_SUCCESS: 'GET_PRODUCT_VARIANTS_SUCCESS',
    GET_PRODUCT_VARIANTS_FAILURE: 'GET_PRODUCT_VARIANTS_FAILURE',

    GET_WISHLIST_REQUEST: 'GET_WISHLIST_REQUEST',
    GET_WISHLIST_SUCCESS: 'GET_WISHLIST_SUCCESS',
    GET_WISHLIST_FAILURE: 'GET_WISHLIST_FAILURE',

    ADD_WISHLIST_ITEM_REQUEST: 'ADD_WISHLIST_ITEM_REQUEST',
    ADD_WISHLIST_ITEM_SUCCESS: 'ADD_WISHLIST_ITEM_SUCCESS',
    ADD_WISHLIST_ITEM_FAILURE: 'ADD_WISHLIST_ITEM_FAILURE',

    REMOVE_WISHLIST_ITEM_REQUEST: 'REMOVE_WISHLIST_ITEM_REQUEST',
    REMOVE_WISHLIST_ITEM_SUCCESS: 'REMOVE_WISHLIST_ITEM_SUCCESS',
    REMOVE_WISHLIST_ITEM_FAILURE: 'REMOVE_WISHLIST_ITEM_FAILURE',
};
