export const UserConstants = {

    FIREBASE_EMAIL_SIGNIN_REQUEST: 'FIREBASE_EMAIL_SIGNIN_REQUEST',
    FIREBASE_EMAIL_SIGNIN_SUCCESS: 'FIREBASE_EMAIL_SIGNIN_SUCCESS',
    FIREBASE_EMAIL_SIGNIN_FAILURE: 'FIREBASE_EMAIL_SIGNIN_FAILURE',

    FIREBASE_FACEBOOK_SIGNIN_REQUEST: 'FIREBASE_FACEBOOK_SIGNIN_REQUEST',
    FIREBASE_FACEBOOK_SIGNIN_SUCCESS: 'FIREBASE_FACEBOOK_SIGNIN_SUCCESS',
    FIREBASE_FACEBOOK_SIGNIN_FAILURE: 'FIREBASE_FACEBOOK_SIGNIN_FAILURE',

    FIREBASE_GOOGLE_SIGNIN_REQUEST: 'FIREBASE_GOOGLE_SIGNIN_REQUEST',
    FIREBASE_GOOGLE_SIGNIN_SUCCESS: 'FIREBASE_GOOGLE_SIGNIN_SUCCESS',
    FIREBASE_GOOGLE_SIGNIN_FAILURE: 'FIREBASE_GOOGLE_SIGNIN_FAILURE',

    FIREBASE_SMS_SIGNIN_REQUEST: 'FIREBASE_SMS_SIGNIN_REQUEST',
    FIREBASE_SMS_SIGNIN_SUCCESS: 'FIREBASE_SMS_SIGNIN_SUCCESS',
    FIREBASE_SMS_SIGNIN_FAILURE: 'FIREBASE_SMS_SIGNIN_FAILURE',

    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

    SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
    SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',

    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
};
